CREATE TABLE book (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isbn             VARCHAR(13)  NOT NULL UNIQUE,
    title            VARCHAR(200) NOT NULL,
    author           VARCHAR(150) NOT NULL,
    category         VARCHAR(50),
    published_year   INT,
    total_copies     INT          NOT NULL,
    available_copies INT          NOT NULL,
    version          BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT chk_book_total_copies CHECK (total_copies >= 0),
    CONSTRAINT chk_book_available_copies CHECK (available_copies >= 0 AND available_copies <= total_copies)
);
