-- Numbers for member codes (M0001, M0002, ...); gaps after rolled-back inserts are harmless.
CREATE SEQUENCE member_code_seq START WITH 1;

CREATE TABLE member (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_code VARCHAR(10)  NOT NULL UNIQUE,
    full_name   VARCHAR(150) NOT NULL,
    email       VARCHAR(254) NOT NULL UNIQUE,
    phone       VARCHAR(30),
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    joined_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    version     BIGINT       NOT NULL DEFAULT 0
);
