CREATE TABLE loan (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id     BIGINT NOT NULL REFERENCES book (id),
    member_id   BIGINT NOT NULL REFERENCES member (id),
    borrowed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    due_date    DATE   NOT NULL,
    returned_at TIMESTAMP WITH TIME ZONE,
    version     BIGINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_loan_book ON loan (book_id);
CREATE INDEX idx_loan_member ON loan (member_id);
CREATE INDEX idx_loan_due_date ON loan (due_date);
