spring:
  application:
    name: library-api
  profiles:
    default: dev
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health
